const __NEXT_DATA__ = {
  "props": {
    "pageProps": {
      "data": {
        "id": 14,
        "name": "Bleach",
        "description": "Kaï / Yabaï - Kurosaki Ichigo, un étudiant de quinze ans aux cheveux orange qui aime la bagarre (comme son père) a la particularité de voir les fantômes ainsi que de pouvoir les toucher. Cela l'amène à rencontrer Kuchiki Rukia, un Shinigami (dieu de la mort) qui combat un Hollow. Le déroulement du combat amène Kuchiki à donner ses pouvoirs à Ichigo qui deviens alors lui même un Shinigami. C'est maintenant à son tour de protéger la ville des Hollows.",
        "kaieur": "Mixouille - Johker",
        "cover": "/images/Bleach/bleach_yabai_affiche.webp",
        "background": "/images/Bleach/background.webp",
        "banner": null,
        "created_at": "2021-04-20T19:22:47.000000Z",
        "updated_at": "2024-01-11T23:15:02.000000Z",
        "deleted_at": null,
        "check": 0,
        "torrents": "Intégrale 28 films@https://nyaa.si/view/1227545",
        "multi": 1,
        "status": "En cours",
        "link": "https://fan-kai.fandom.com/fr/wiki/Bleach_Yabai_(Johker)",
        "seasons": [
          {
            "id": 20,
            "serie_id": 14,
            "name": "Shinigami Remplaçant",
            "number": 1,
            "cover": "/images/Bleach/bleach_season_1_new.webp",
            "created_at": "2021-04-20T19:22:47.000000Z",
            "updated_at": "2021-10-08T04:43:55.000000Z",
            "deleted_at": null,
            "episodes": [
              {
                "id": 824,
                "serie_id": 14,
                "season_id": 20,
                "name": "Death and Strawberry",
                "number": 1,
                "path_jap": "/BleachKai/01/01_jap_final.m3u8",
                "path_fr": "/BleachKai/01/01_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film1.webp",
                "duration": "0:52:59",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T10:57:27.000000Z",
                "updated_at": "2023-11-15T07:50:13.000000Z",
                "deleted_at": null,
                "description": "Ichigo Kurosaki est un adolescent capable de voir les fantômes. Il devient un Shinigami après avoir récupéré une partie des pouvoirs de sa nouvelle amie Rukia Kuchiki.",
                "episodes": "1 - 3",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 825,
                "serie_id": 14,
                "season_id": 20,
                "name": "Memories in the rain",
                "number": 2,
                "path_jap": "/BleachKai/02/02_jap_final.m3u8",
                "path_fr": "/BleachKai/02/02_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film2.webp",
                "duration": "1:42:21",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T10:59:48.000000Z",
                "updated_at": "2023-11-15T08:04:42.000000Z",
                "deleted_at": null,
                "description": "Chad devient le propriétaire d'une perruche maudite. D'après l'ami qui la lui confie, tous ceux qui s'en sont occupés sont morts mystérieusement. Le lendemain, lorsque Chad apporte la perruche au lycée, Rukia et Ichigo ressentent la présence d'un esprit dans la cage.",
                "episodes": "4 - 9",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 826,
                "serie_id": 14,
                "season_id": 20,
                "name": "Quincy Archer hates you",
                "number": 3,
                "path_jap": "/BleachKai/03/03_jap_final.m3u8",
                "path_fr": "/BleachKai/03/03_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film3.webp",
                "duration": "1:39:00",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:00:07.000000Z",
                "updated_at": "2023-11-15T08:04:59.000000Z",
                "deleted_at": null,
                "description": "Une émission de chasse aux fantômes très populaire au Japon est diffusée dans le quartier d'Ichigo et de ses amis ; il est bien le seul à ne pas aimer ce genre de show... Malgré cela, il décide d'accompagner sa famille.",
                "episodes": "10 - 14",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 827,
                "serie_id": 14,
                "season_id": 20,
                "name": "The Blade And Me",
                "number": 4,
                "path_jap": "/BleachKai/04/04_jap_final.m3u8",
                "path_fr": "/BleachKai/04/04_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film4.webp",
                "duration": "1:49:51",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:00:24.000000Z",
                "updated_at": "2023-11-15T08:08:23.000000Z",
                "deleted_at": null,
                "description": "Blessé par la négligence d'Ichigo, Kon décide de fuguer. Malheureusement pour lui, cette escapade ne sera qu'une succession de déboires. Il se fera notamment maltraiter par des filles de la classe d'Ichigo ainsi que par Jinta et Ururu de la boutique d'Urahara.",
                "episodes": "15 - 20",
                "enough_check": 0,
                "multi": 1
              }
            ]
          },
          {
            "id": 76,
            "serie_id": 14,
            "name": "Soul Society",
            "number": 2,
            "cover": "/images/Bleach/bleach_season_2_.webp",
            "created_at": "2021-04-25T17:20:01.000000Z",
            "updated_at": "2021-10-08T04:41:43.000000Z",
            "deleted_at": null,
            "episodes": [
              {
                "id": 828,
                "serie_id": 14,
                "season_id": 76,
                "name": "Fourteen days for conspiracy",
                "number": 5,
                "path_jap": "/BleachKai/05/05_jap_final.m3u8",
                "path_fr": "/BleachKai/05/05_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film5.webp",
                "duration": "1:30:47",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:24:18.000000Z",
                "updated_at": "2023-11-15T08:09:22.000000Z",
                "deleted_at": null,
                "description": "Le groupe finit par pénétrer dans le monde de la Soul Society. Ils se retrouvent dans le Rukongai, la partie où les âmes errantes circulent. Ichigo décide de passer le portail de la voie blanche permettant d'accéder au Seireitei, la partie où vivent les Shinigamis.",
                "episodes": "21 - 25",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 829,
                "serie_id": 14,
                "season_id": 76,
                "name": "Intruderz",
                "number": 6,
                "path_jap": "/BleachKai/06/06_jap_final.m3u8",
                "path_fr": "/BleachKai/06/06_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film6.webp",
                "duration": "1:39:28",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:24:35.000000Z",
                "updated_at": "2023-11-15T08:09:01.000000Z",
                "deleted_at": null,
                "description": "Pour prévenir leur atterrissage, chaque groupe improvise : tandis qu'Inoue utilise le « Triple lien sacré du bouclier », Ganju utilise le « Tournement du sable », pour ralentir la chute ; Yoruichi n'a besoin que de son agilité pour amortir sa chute, devant quelques Shinigami qui n'ont que le temps de l'apercevoir avant sa rapide disparition.",
                "episodes": "26 - 32",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 830,
                "serie_id": 14,
                "season_id": 76,
                "name": "The Dead & the Undead",
                "number": 7,
                "path_jap": "/BleachKai/07/07_jap_final.m3u8",
                "path_fr": "/BleachKai/07/07_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film7.webp",
                "duration": "1:46:54",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:29:11.000000Z",
                "updated_at": "2023-11-15T08:09:52.000000Z",
                "deleted_at": null,
                "description": "Après avoir battu Renji, Ichigo s'écroule à son tour. Ganju et Hanataro l'emportent dans les sous-sols pour pouvoir le soigner, évitant l'arrivée des renforts, mené par le lieutenant de la troisième division, Izuru Kira. Celui-ci veille Renji avec Momo Hinamori, lieutenant de la cinquième division, tous deux ayant été des compagnons d'étude de Renji.",
                "episodes": "34 - 40",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 831,
                "serie_id": 14,
                "season_id": 76,
                "name": "Secrets of the Moon",
                "number": 8,
                "path_jap": "/BleachKai/08/08_jap_final.m3u8",
                "path_fr": "/BleachKai/08/08_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film8.webp",
                "duration": "1:33:44",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:29:54.000000Z",
                "updated_at": "2023-11-15T08:10:10.000000Z",
                "deleted_at": null,
                "description": "La petite Yachiru remercie Ichigo d'avoir donné autant de plaisir à Kenpachi Zaraki lors de ce combat. Ichigo est mourant, Kenpachi est emmené par Yachiru. Cette dernière se souvient du moment où ils se sont rencontrés.",
                "episodes": "40 - 45",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 832,
                "serie_id": 14,
                "season_id": 76,
                "name": "Suspicion for Assassination",
                "number": 9,
                "path_jap": "/BleachKai/09/09_jap_final.m3u8",
                "path_fr": "/BleachKai/09/09_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film9.webp",
                "duration": "1:15:39",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2021-05-13T11:31:03.000000Z",
                "updated_at": "2023-11-15T08:10:29.000000Z",
                "deleted_at": null,
                "description": "Tôsen Kaname, le capitaine de la 9e division endort Uryû avec le pouvoir de son Zanpakuto. De son côté, après avoir écouté les explications de Yoruichi, Ichigo commence son entraînement.",
                "episodes": "45 - 51",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 1458,
                "serie_id": 14,
                "season_id": 76,
                "name": "No Goodbye",
                "number": 10,
                "path_jap": "/BleachKai/10/10_jap_final.m3u8",
                "path_fr": "/BleachKai/10/10_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film10.webp",
                "duration": "2:05:39",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2023-11-01T15:26:25.000000Z",
                "updated_at": "2023-11-15T08:10:56.000000Z",
                "deleted_at": null,
                "description": "Alors que des Shinigami masqués sortent Rukia de sa cellule pour l'emmener au lieu de l'exécution, Kenpachi Zaraki court en portant Yachiru et Orihime sur le dos, suivi d'Ikkaku, Yumichika et d'Aramaki. Orihime indique la direction à Zaraki mais Yachiru en choisit une autre.",
                "episodes": "51 - 57",
                "enough_check": 0,
                "multi": 1
              },
              {
                "id": 1459,
                "serie_id": 14,
                "season_id": 76,
                "name": "End of Hypnosis",
                "number": 11,
                "path_jap": "/BleachKai/11/11_jap_final.m3u8",
                "path_fr": "/BleachKai/11/11_fr_final.m3u8",
                "cover": "/images/Bleach/Bleach-Yabai_Film11.webp",
                "duration": "2:00:32",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2023-11-01T15:27:58.000000Z",
                "updated_at": "2023-11-15T08:11:20.000000Z",
                "deleted_at": null,
                "description": "Combat intense entre Ichigo et Byakuya Kuchiki. Ichigo provoque le capitaine de la 6e division pour qu'il libère son bankai. Byakuya libère alors son bankai : Senbonzakura Kageyoshi, des lames immenses surgissent du sol.",
                "episodes": "58 - 64",
                "enough_check": 0,
                "multi": 1
              }
            ]
          },
          {
            "id": 77,
            "serie_id": 14,
            "name": "Arrancars",
            "number": 3,
            "cover": "/images/Bleach/bleach_season_3.webp",
            "created_at": "2021-04-25T17:21:33.000000Z",
            "updated_at": "2021-10-13T21:28:14.000000Z",
            "deleted_at": null,
            "episodes": [
              {
                "id": 1233,
                "serie_id": 14,
                "season_id": 77,
                "name": "Eyes of the Unknown",
                "number": 12,
                "path_jap": null,
                "path_fr": null,
                "cover": "/images/Bleach/Bleach-Yabai_Film12.webp",
                "duration": "01:39:34",
                "check": 0,
                "custom_cover": 1,
                "created_at": "2023-04-15T08:59:12.000000Z",
                "updated_at": "2025-04-21T14:37:34.000000Z",
                "deleted_at": null,
                "description": "Ichigo rencontre Shinji Hirako, un mystérieux nouveau venu qui lui propose de rejoindre les Vizards. Alors que Grand Fisher, devenu Arrancar, menace Karakura, Ichigo se retrouve confronté à son propre hollow intérieur. Les tensions montent avec l'apparition de puissants ennemis, et des révélations sur les véritables intentions des Arrancars commencent à émerger.",
                "episodes": "110 - 115",
                "enough_check": 0,
                "multi": 1
              },
              // ... (autres épisodes de la saison 3)
            ]
          },
          {
            "id": 79,
            "serie_id": 14,
            "name": "Fullbring",
            "number": 4,
            "cover": "/images/Bleach/bleach_season_4.webp",
            "created_at": "2021-04-25T17:21:33.000000Z",
            "updated_at": "2021-10-13T21:28:14.000000Z",
            "deleted_at": null,
            "episodes": [
              {
                "id": 1655,
                "serie_id": 14,
                "season_id": 79,
                "name": "Welcome to Our Xcution",
                "number": 26,
                "path_jap": null,
                "path_fr": null,
                "cover": "/images/Bleach/Bleach-Yabai_Film26.webp",
                "duration": "02:04:28",
                "check": 1,
                "custom_cover": 1,
                "created_at": "2024-11-11T23:19:04.000000Z",
                "updated_at": "2025-04-21T14:59:15.000000Z",
                "deleted_at": null,
                "description": "Dix-sept mois après la guerre, Ichigo mène une vie calme, loin des ténèbres du passé. Mais une rencontre fortuite réveille des échos de son ancien destin. Alors que des ombres du passé resurgissent, des questions sans réponses hantent ses jours. La tranquillité d'une vie \"normale\" est-elle vraiment ce qu'il désire ?",
                "episodes": "343 - 350",
                "enough_check": 0,
                "multi": 1
              },
              // ... (autres épisodes de la saison 4)
            ]
          }
        ]
      }
    }
  },
  "__N_SSG": true,
  "page": "/productions/[id]",
  "query": {
    "id": "14"
  },
  "buildId": "XHri0mrrgwsMtC4699GIK",
  "isFallback": false,
  "gsp": true,
  "scriptLoader": []
};

// Rendre les données disponibles globalement
window.__NEXT_DATA__ = __NEXT_DATA__;